services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - images:/app/public/images
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/neva
      - PRISMA_CLIENT_OUTPUT=/app/generated/prisma
    env_file:
      - backend/.env
    command: ['tail', '-f', '/dev/null']

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=neva
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  images:
  db_data:

networks:
  neva-network:
    driver: bridge
